# Generated by Django 5.0.1 on 2024-01-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_teniss_court_timeslot_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adineh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='reservation',
        ),
    ]
