# Generated by Django 5.0.1 on 2024-01-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_adineh_delete_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='adineh',
            name='is_paid',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=0),
        ),
    ]
