# Generated by Django 5.0.1 on 2024-02-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_timeslot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adineh',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
