# Generated by Django 5.0.1 on 2024-02-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_adineh_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='texts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre1', models.CharField(max_length=500, verbose_name='تیتر صفحه اصلی')),
                ('text1', models.TextField(verbose_name='متن صفحه اصلی')),
                ('titre2', models.CharField(max_length=500, verbose_name='تیتر صفحه آدینه')),
                ('text2', models.TextField(verbose_name='متن صفحه آدینه')),
                ('titre3', models.CharField(max_length=500, verbose_name='تیتر صفحه روز های هفته')),
                ('text3', models.TextField(verbose_name='متن صفحه روز های هفته')),
                ('titre4', models.CharField(max_length=500, verbose_name='تیتر صفحه تایم های آن روز')),
                ('text4', models.TextField(verbose_name='متن صفحه تایم های آن روز')),
                ('titre5', models.CharField(max_length=500, verbose_name='تیتر صفحه مسابفه دهندگان')),
                ('text5', models.TextField(verbose_name='متن صفحه مسابقه دهندگان')),
                ('titre6', models.CharField(max_length=500, verbose_name='تیتر صفحه صورتحساب آدینه')),
                ('text6', models.TextField(verbose_name='متن صفحه صورتحساب آدینه')),
                ('titre7', models.CharField(max_length=500, verbose_name='تیتر صفحه صورت حساب رزرو تایم')),
                ('text7', models.TextField(verbose_name='متن صفحه رزرو تایم')),
                ('titre8', models.CharField(max_length=500, verbose_name='تیتر صفحه وارد کردن مشخصات رزرو تایم')),
                ('text8', models.TextField(verbose_name='متن صفحه وارد کردن مشخصات رزرو تایم')),
            ],
        ),
    ]
